ALTER TABLE meetings ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'PENDING';
ALTER TABLE meetings ADD COLUMN IF NOT EXISTS responded_by_user_id UUID REFERENCES users(id);
ALTER TABLE meetings ADD COLUMN IF NOT EXISTS responded_at TIMESTAMP;

UPDATE meetings
SET status = 'PENDING'
WHERE status IS NULL;
